# Generated by Django 4.2 on 2023-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Zadejte označení filmového žánru (např. sci-fi, komedie)', max_length=50, unique=True, verbose_name='Název žánru'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Zadejte název filmu', max_length=200, verbose_name='Název filmu')),
                ('plot', models.TextField(blank=True, null=True, verbose_name='Děj')),
                ('release_date', models.DateField(blank=True, help_text='Zadejte, prosím, datum ve formátu: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Datum uvedení')),
                ('runtime', models.PositiveSmallIntegerField(blank=True, help_text='Prosím, zadejte celočíselný údaj vyjadřující délku filmu v minutách', null=True, verbose_name='Délka filmu')),
                ('rating', models.FloatField(default=5.0, help_text='Zadejte desetinné číslo v rozsahu 0.0 až 10.0', null=True, verbose_name='Hodnocení')),
                ('genres', models.ManyToManyField(help_text='K označení většího počtu žánrů můžete stisknout klávesu CTRL', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
                'ordering': ['-release_date', 'title'],
            },
        ),
    ]
