# Generated by Django 4.2 on 2023-05-17 14:00

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_name_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(help_text='K označení většího počtu žánrů můžete stisknout klávesu CTRL', to='movies.genre', verbose_name='Žánry'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, help_text='Zadejte, prosím, datum ve formátu: <em>den.měsíc.rok</em>', null=True, verbose_name='Datum uvedení'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Doplňte stručný popis přílohy (do 200 znaků)', max_length=200, verbose_name='Titulek přílohy')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Vložte soubor s požadovanou přílohou', null=True, upload_to=movies.models.Attachment.attachment_path, verbose_name='Příloha')),
                ('type', models.CharField(blank=True, choices=[('audio', 'audio'), ('obrázek', 'obrázek'), ('text', 'text'), ('video', 'video'), ('jiná', 'jiná')], default='obrázek', help_text='Vyberte některý z uvedených typů příloh', max_length=10, verbose_name='Typ přílohy')),
                ('film', models.ForeignKey(help_text='Vyberte film, s nímž má být příloha spojena', on_delete=django.db.models.deletion.CASCADE, to='movies.film', verbose_name='Film')),
            ],
            options={
                'ordering': ['-last_update', 'type'],
            },
        ),
    ]
