# Generated by Django 4.2 on 2023-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_film_genres_alter_film_release_date_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-last_update', 'type'], 'verbose_name': 'Příloha', 'verbose_name_plural': 'Přílohy'},
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, help_text='Zde můžete přiložit grafický soubor s filmovým plakátem', null=True, upload_to='posters', verbose_name='Plakát k filmu'),
        ),
    ]
