# Generated by Django 4.2 on 2023-05-17 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(default=5.0, help_text='Zadejte desetinné číslo v rozsahu 0.0 až 10.0', null=True, validators=[django.core.validators.MinValueValidator(0, 'Hodnota nesmí být menší než 0!'), django.core.validators.MaxValueValidator(10, 'Hodnota nesmí být větší než 10!')], verbose_name='Hodnocení'),
        ),
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Prosím, zadejte celočíselný údaj vyjadřující délku filmu v minutách', null=True, validators=[django.core.validators.MaxValueValidator(1000, 'Hodnota nesmí být větší než 1000!')], verbose_name='Délka filmu'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(help_text='Zadejte název filmu', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Název nesmí být kratší než 2 znaky!'), django.core.validators.RegexValidator('^[^+\\-*/%&;:.,]', 'Název nesmí začínat speciálním znakem!')], verbose_name='Název filmu'),
        ),
    ]
